WebFashion/Controllers/OrderProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFashion.Models;

namespace WebFashion.Controllers
{
    public class OrderProductsController : Controller
    {
        // GET: OrderProducts
        private DBFashionEntities db = new DBFashionEntities();
        public ActionResult Index()
        {
            var orderproes = db.OrderProes.ToList();
            return View(orderproes);
        }
        public ActionResult Detail(int id)
        {
            return View(db.OrderProes.Where(s => s.ID == id).FirstOrDefault());
        }
        public ActionResult Partial_OrderDetail(int id)
        {
            var items = db.OrderDetails.Where(x => x.IDOrder == id).ToList();
            return PartialView(items);
        }
        public ActionResult Accept(int ID)
        {
            OrderPro _order = db.OrderProes.Find(ID);
            _order.Status = 1;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebFashion/Views/OrderProducts/Detail.cshtml
@model WebFashion.Models.OrderPro
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Orders List</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="/OrderProducts/Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Order List</a>
            <span class="breadcrumb-item active">Orders Detail</span>
        </nav>
    </div>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Info Customer</h4>
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td>ID Cus:</td>
                                    <td class="text-dark font-weight-semibold"> @Html.DisplayFor(model => model.IDCus)</td>
                                </tr>
                                <tr>
                                    <td>Name:</td>
                                    <td class="text-dark font-weight-semibold"> @Html.DisplayFor(model => model.NameCus)</td>
                                </tr>
                                <tr>
                                    <td>Phone:</td>
                                    <td>	@Html.DisplayFor(model => model.PhoneCus)</td>
                                </tr>
                                <tr>
                                    <td>Address:</td>
                                    <td>	@Html.DisplayFor(model => model.AddressDeliverry)</td>
                                </tr>
                                <tr>
                                    <td>Date Order:</td>
                                    <td>	@Html.DisplayFor(model => model.DateOrder)</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>ID Product</th>
                        <th>Name Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
                    @Html.Action("Partial_OrderDetail", "OrderProducts", new { id = Model.ID })
                </tbody>
            </table>
        </div>
    </div>
</div>

WebFashion/Views/OrderProducts/Index.cshtml
@model IEnumerable<WebFashion.Models.OrderPro>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Orders List</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Orders List</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Customer</th>
                        <th>Date</th>
                        <th>Phone Number</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            #@item.ID
                        </td>
                        <td>
                            <div class="d-flex align-items-center">
                                <h6 class="m-b-0">@item.NameCus</h6>
                            </div>
                        </td>
                        <td>@item.DateOrder</td>
                        <td>@item.PhoneCus</td>
                        @{
                            if (@item.Status == 0)
                            {
                                <td><a href="/OrderProducts/Accept/@item.ID" type="button" class="btn btn-warning">Xác nhận</a></td>
                            }
                            else if (@item.Status == 1)
                            {
                                <td><button type="button" class="btn btn-primary">Đã xác nhận</button></td>
                            }
                            else if (@item.Status == 2)
                            {
                                <td><button type="button" class="btn btn-danger">Đã hủy</button></td>
                            }

                        }
                        <td class="text">
                            <a href="/OrderProducts/Detail/@item.ID" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                <i class="anticon anticon-info"></i>
                            </a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

WebFashion/Views/OrderProducts/Partial_OrderDetail.cshtml
@model IEnumerable<WebFashion.Models.OrderDetail>
@if (Model != null && Model.Any())
{
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                #@item.ID
            </td>
            <td>
                @item.IDProduct
            </td>
            <td>
                @item.NamePro
            </td>
            <td>
                @item.Quantity
            </td>
            <td>
                @string.Format("{0:#,##0} VND", item.UnitPrice)
            </td>
            <td>
                @string.Format("{0:#,##0} VND", item.UnitPrice * item.Quantity) VND
            </td>
        </tr>
        }
    </tbody>

}